= Gradle Semantic Versioning Release
:sectnums:
:toc:
:toclevels: 4
:idprefix: id_

This project is inspired by the https://github.com/vivin/gradle-semantic-build-versioning[Semantic build-versioning for Gradle] plugin.

== Introduction

This is a Gradle plugin that provides support for https://semver.org/[semantic versioning] of builds. It is quite easy to use and extremely configurable. The plugin allows you to bump the major, minor, patch or pre-release version based on the latest version, which is identified from a git tag. It also allows you to bump pre-release versions based on a scheme that you define. The version can be bumped by using version-component-specific project properties or can be bumped automatically based on the contents of a commit message. If no manual bumping is done via commit message or project property, the plugin will increment the version-component with the lowest precedence; this is usually the patch version, but can be the pre-release version if the latest version is a pre-release one. The plugin does its best to ensure that you do not accidentally violate semver rules while generating your versions; in cases where this might happen the plugin forces you to be explicit about violating these rules.

== Usage

[source,kotlin]
----
id("io.github.sfali23.gradle-semantic-versioning-release") version ("0.3.0")
----

== Plugin Settings
The following are plugin settings:

=== Default Settings

The following are the default settings, each configuration are be explained below:

[source, kotlin]
----
import semverrelease.AutoBump
import semverrelease.ComponentToBump
import semverrelease.PreReleaseConfig
import semverrelease.SnapshotConfig

semverrelease {
    startingVersion.set("0.1.0")
    tagPrefix.set("v")
    forceBump.set("false")
    newPreRelease.set("false")
    promoteToRelease.set("false")
    defaultBumpLevel.set(ComponentToBump.PATCH)
    snapshotConfig.set(SnapshotConfig(prefix = "SNAPSHOT", appendCommitHash = true, useShortHash = true))
    preReleaseConfig.set(PreReleaseConfig(prefix = "RC", startingVersion = 1, separator = "."))
    autoBump.set(AutoBump(majorPattern = "\\[major]".toRegex(), minorPattern = "\\[minor]".toRegex(), patchPattern = "\\[patch]".toRegex(),
        newPreReleasePattern = "\\[new-pre-release]".toRegex(), promoteToReleasePattern = "\\[promote]".toRegex()))
    hotfixBranchPattern.set("^v(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\+$".toRegex())
}
----

[[id_starting_version]]
=== startingVersion
This option defines the starting version of the build in case there is no tag available to determine the next version. The default
value is *0.1.0*.

=== tagPrefix
This option defines the prefix to use when tagging a release. The default value is *v*.

[[id_forcebump]]
=== forceBump (Manual bump)
This property defines the flag to enable force bump. The default value is *false*. To force bump to work, you have to set <<id_component_to_bump, componentToBump>> property.

[[id_new_pre_release]]
=== newPreRelease
This property defines the flag to enable new-pre-release. The default value is *false*. This property can be set either by setting value to `true` in `build.gradle` file as described above or by by adding a specific pattern in your commit message, default value is *[new-pre-release]*. See <<id_custom_auto_bump_pattern, here>> on how to customize this value.

This property creates a new pre-release version by bumping the requested version-component and then adding the starting pre-release version from the pre-release configuration (see <<id_pre_releases, pre-release>>). It has the following behavior:

* When used by itself, it will bump the patch version and then append the starting pre-release version as specified in the
pre-release configuration. Assuming that the base version is `x.y.z`, the new version will be `x.y.(z + 1)-<startingVersion>`
(see <<id_pre_release_starting_version, `startingVersion`>>), for example, **1.2.2** will become **1.2.3-RC.1**.
* When used with `componentToBump=patch` or `[patch]` commit message, the behavior is the same as using `newPreRelease` by itself.
* When used with `componentToBump=minor` or `[minor]` commit message, it will bump the minor version and then append the starting pre-release version as
specified in the pre-release configuration. Assuming that the base version is `x.y.z`, the new version will be `x.(y + 1).0-<startingVersion>`
(see <<id_pre_release_starting_version, `startingVersion`>>), for example, **1.2.2** will become **1.3.0-RC.1**.
* When used with `componentToBump=major` or `[major]` commit message, it will bump the major version and then append the starting pre-release version as
specified in the pre-release configuration. Assuming that the base version is `x.y.z`, the new version will be `(x + 1).0.0-<startingVersion>`
(see <<id_pre_release_starting_version, `startingVersion`>>), for example, **1.2.2** will become **2.0.0-RC.1**.

If you use auto-bumping (see <<id_autobump_on_commit, Automatic bumping based on commit messages>>) and
manual bumping together; then force bump will take precedence.

==== Bump pre-release version
Once a new pre-release version is created any subsequent bump will only bump the pre-release version, any attempt to bump either of `major`, `minor`, or `patch` version will be ignored, either by _forceBump_ or _autoBump_, for example, if the pre-release version is *1.2.3-RC.1*, then next version will be *1.2.3-RC.2*.

[[id_default_bump_level]]
=== defaultBumpLevel
This property defines the default bump level for <<id_autobump_on_commit, auto-bump>> strategy. Default value is `PATCH`.

[[id_component_to_bump]]
=== componentToBump
This property bumps the given version. It can be set to the values `MAJOR`, `MINOR`, or `PATCH`. This property is **required** if you are using <<id_forcebump, force bump>>. This property has no effect when using <<id_autobump_on_commit, auto-bump>>.

Assuming that the base version is `x.y.z`, and the value of `componentToBump` is:

MAJOR::
The new version will be `(x + 1).0.0`; if the base version is a pre-release version, the pre-release version-component is
discarded, and the new version will still be `(x + 1).0.0`.

MINOR::
The new version will be `x.(y + 1).0`; if the base version is a pre-release version, the pre-release version-component is
discarded, and the new version will still be `x.(y + 1).0`.

PATCH::
The new version will be `x.y.(z + 1)`; if the base version is a pre-release version, the pre-release version-component is
discarded, and the new version will still be `x.y.(z + 1)`.

[[id_promote_to_release]]
=== promoteToRelease
This property defines the flag to enable promote-to-release. The default value is *false*. This option can be set either by setting value `true` via `build.gradle` or via *[promote]* in the commit message.

This property promotes a pre-release version to a release version. This is done by discarding the pre-release version-component.
For example, assuming that the base version is `x.y.z-RC.2`, the new version will be `x.y.z`.
*This property can only be used if the base version is a pre-release version*.

[[id_pre_releases]]
=== Pre-releases
This is how you can define your pre-release versioning-strategy. This is a special case because other than defining a basic
syntax and ordering rules, the semantic-versioning specification has no other rules about pre-release identifiers. This means
that some extra configuration is required if you want to generate pre-release versions.

==== prefix and separator
These options define `prefix` and `separator` of pre-release version. The default values for `prefix` and `separator` are `RC` and `.` respectively.

[[id_pre_release_starting_version]]
==== startingVersion
This option is required and describes the starting pre-release version of a new pre-release. This value will be used if
<<id_new_pre_release, `newPreRelease`>> is invoked (either explicitly or via <<id_autobump_on_commit, Automatic bumping based on commit messages>>).
The default value is `1`, this value has to greater or equal to 1.

[[id_autobump_on_commit]]
=== Automatic bumping based on commit messages
Sometimes you might want to automatically bump your version as part of your continuous-integration process. Without this option,
you would have to explicitly configure your CI process to use the corresponding `componentToBump` property value, depending on
the version component you want to bump. This is because the default behavior of the plugin is to bump the component with the
least precedence. Instead, you can configure the plugin to automatically bump the desired version-component based on the contents
of all your commit messages since the nearest ancestor-tags; this essentially means messages from all unreleased ancestor-commits.
If multiple commit-messages apply, then the component with the highest precedence wins. This way you can note in each commit
message whether the change is major or minor directly, and this plugin uses that information to calculate the next version-number to be used.

==== autoBump
This option allows you to specify how the build version should be automatically bumped based on the contents of commit messages. The
full message of each applicable commit-message is checked to see if a match for any of specified pattern can be found. Note that in
the case of multiple matches, the component with the highest precedence wins. This option has the following sub-options:

majorPattern::
If any relevant commit message contains a match for `majorPattern`, the major version will be bumped. This has to be a regular
expression, and its default value is `\[major\]`, which means `[major]` anywhere in the commit message.

minorPattern::
If any relevant commit message contains a match for `minorPattern`, the minor version will be bumped. This has to be a regular
expression, and its default value is `\[minor\]`, which means `[minor]` anywhere in the commit message.

patchPattern::
If any relevant commit message contains a match for `patchPattern`, the patch version will be bumped. This has to be a regular
expression, and its default value is `\[patch\]`, which means `[patch]` anywhere in the commit message.

newPreReleasePattern:: If any relevant commit message contains a match for `newPreReleasePattern`, then a new pre-release version
will be created. If no major or minor-version bumping is specified via autobumping or manually, the new pre-release version will
be created after bumping the patch version. Otherwise, the new pre-release version is created after bumping the appropriate component.
The same restrictions and rules that apply to the <<id_new_pre_release, `newPreRelease`>> property apply here as well. This has to be a
regular expression, and its default value is `\[new-pre-release\]`, which means `[new-pre-release]` anywhere in the message.

promoteToReleasePattern::
If any relevant commit message contains a match for `promoteToReleasePattern`, the version will be promoted to a release version.
The same rules that apply to the <<id_promote_to_release,`promoteToRelease`>> property apply here as well. This has to be a regular
expression, and its default value is `\[promote\]`, which means `[promote]` anywhere in any line.

[[id_custom_auto_bump_pattern]]
.Defining custom patterns to be used by `autoBump`
====
[source, kotlin]
----
import semverrelease.AutoBump

semverrelease {
    autoBump.set(AutoBump(
        // match "[bump-major]" on its own line without leading or trailing characters
        majorPattern = "(?m)^\\[bump-major\\]$".toRegex(),
         // match "[bump-minor]" on its own line without leading or trailing characters
        minorPattern = "(?m)^\\[bump-minor\\]$".toRegex(),
        // match "[bump-patch]" on its own line without leading or trailing characters
        patchPattern = "(?m)^\\[bump-patch\\]$".toRegex(),
        newPreReleasePattern = "(?m)^\\[make-new-pre-release\\]$".toRegex(),
        // match "[promote-to-release]" on its own line without leading or trailing characters
        promoteToReleasePattern = "\(?m)^\\[promote-to-release\\]$".toRegex()))
}
----
====

[NOTE]
====
If none of the commit messages match the patterns in `autoBump`, the plugin assumes its default behavior and will use <<id_default_bump_level, defaultBumpLevel>> property.
====

=== extraReleaseBranches
By default, this plugin will only allow to release from either from `main` or `master` branches. This option provides name of the branches you wish to release from, for example, `development`. If the branch is not `main`, `master`, or one of the branch in `extraReleaseBranches`then snapshot version will be created.

=== snapshot config
This option defines how snapshot versions will be tagged, format of the snapshot version will, x.y.z-SNAPSHOT+<commit_has>. There three parts in this property:

==== Snapshot prefix
Th Default value is *SNAPSHOT*.

==== appendCommitHash
This option specifies whether to include the commit hash as part of the snapshot version. The default value is *true*. If _false_ no commit has will be appended and a snapshot version will be `x.y.z-SNAPSHOT`.

==== useShortHash
This option specifies whether to use a short commit hash. The default value is *true*. If this value is set to _false_ then the full commit hash will be used.

=== snapshot
This option defines the flag to make the current release a snapshot release. This option is calculated as follows:

. The option is explicitly set in `build.gradle` using `snapshot` property.
. The option is set via `hasUncommittedChanges` function of `Git`. If the function returns *true* then `snapshot` flag will be
set to *true*, *false* otherwise.
. If the current branch is one of `main, `master`, or specified in `extraReleaseBranches`.

=== hotfixBranchPattern &mdash; Checking out a tag
It is useful to check out a tag when you want to create a build of an older version. Once you check out specific tag create a branch by using the following pattern: `<tag-prefix>major.minor.patch+`, for example, if the tag was `v1.2.3` then branch name should be `v1.2.3+`. Any subsequent build will only bump `hot fix` version, so next version will be, `v1.2.3.1` and so on. **It is not possible to bump any other part of the version once you have a tag checked out.**

=== unReleasedCommits
Collects unreleased commits to be added into `releaseTagComment` if `addUnReleasedCommitsToTagComment` settings is set to __true__.

=== addUnReleasedCommitsToTagComment
Default comment of the release tag is `Release <version_to_be_released>`, this setting allows to add un-released commits to tag summary. With setting on tag comment will be:

[source]
----
Release <version_to_be_released>


Commit(<short_hash>, <commit_message>)
----
